<?php

/**
 * @file
 * Wire functions for Etype Services to allow Editors to import and publish
 *   stories from other publications
 *
 */

/**
 * Implements hook_permission().
 */
function etype_wire_permission() {
  return [
    'access wire content' => [
      'title' => t('Access Wire Content'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function etype_wire_menu() {

  $items = [];

  /* display wire content */
  $items['admin/content/wirecontent'] = [
    'title' => 'Wire Content',
    'description' => "Publish stories from other publications.",
    'page callback' => 'etype_wire_admin_content',
    'access callback' => 'user_access',
    'access arguments' => ['access wire content'],
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/wirecontent.admin.inc',
  ];

  /* to add wire content to site */
  $items['admin/wirecontent/%/add'] = [
    'title' => 'Add Wire Content',
    'description' => "Add content from other sites to this one.",
    'page callback' => 'etype_wire_node_add',
    'page arguments' => [2],
    'access arguments' => ['access wire content'],
    'type' => MENU_CALLBACK,
    'file' => 'includes/wirecontent.add.inc',
  ];

  /* to be able to run cron job from url */
  $items['admin/wirecontent/cron'] = [
    'title' => 'Wire Content',
    'description' => "Run Wire cron job.",
    'page callback' => 'etype_wire_node_export',
    'access arguments' => ['access wire content'],
    'type' => MENU_CALLBACK,
    'file' => 'includes/wirecontent.cron.inc',
  ];

  /* admin settings page */
  $items['admin/config/etype_wire'] = [
    'title' => 'eType',
    'description' => 'eType Settings',
    // Like any other menu item
    'position' => 'right',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => ['administer site configuration'],
    // Permission needed to view this area
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  ];

  $items['admin/config/etype_wire/settings'] = [
    'title' => 'Wire Content',
    'description' => 'Wire content options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_wire_admin'],
    'access arguments' => ['access wire content'],
    'file' => 'includes/wirecontent.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];


  return $items;
}

/**
 * @param $op
 * @param null $job
 *
 * @return mixed
 */
function etype_wire_cronapi($op, $job = NULL) {

  $items['etype_wire_cron'] = [
    'description' => 'Export Nodes to Wire Content',
    'rule' => '0 0,12 * * *',
    'callback' => 'etype_wire_node_export',
    'arguments' => ['all'],
    'file' => 'includes/wirecontent.cron.inc',
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function etype_wire_theme() {
  $theme = [
    'wire_admin_content' => [
      'variables' => ['nodes' => NULL],
      'file' => 'includes/wirecontent.admin.inc',
    ],
  ];
  return $theme;
}

/**
 * Connect to wire db
 *
 * @return \PDO
 */
function _etype_wire_connect() {
  try {
    $dbHandle = new PDO("mysql:host=35.196.56.75;dbname=wire", 'etype_wire', 'GeMay9k60gL1=2Q');
    $dbHandle->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    // always disable emulated prepared statement when using the MySQL driver
    $dbHandle->setAttribute(PDO::ATTR_EMULATE_PREPARES, FALSE);
  } catch (Exception $e) {
    watchdog('etype_wire', 'There was an error connecting to the database.',
      [], WATCHDOG_ERROR);
  }
  return $dbHandle;
}
