<?php

/**
 * Implements hook_block_info().
 */
function etype_block_info() {
  $blocks = array();

  $blocks['Social'] = array(
    'info' => t('Social'),
  );
  
  $blocks['Follow'] = array(
    'info' => t('Follow'),
  );

  $blocks['Facebook'] = array(
    'info' => t('Facebook'),
  );

  $blocks['Twitter'] = array(
    'info' => t('Twitter'),
  );

  $blocks['e-Edition'] = array(
    'info' => t('e-Edition'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function etype_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'Social':
      $block['subject'] = '';
      $block['content'] = _etype_social_content();
      break;
    
    case 'Follow':
      $block['subject'] = 'Follow Us';
      $block['content'] = _etype_follow_content();
      break;
    
    case 'Facebook':
      $block['subject'] = 'Facebook';
      $block['content'] = _etype_facebook_content();
      break;

    case 'Twitter':
      $block['subject'] = 'Twitter';
      $block['content'] = _etype_twitter_content();
      break;

    case 'e-Edition':
      $block['subject'] = '';
      $block['content'] = _etype_e_edition_content();
      break;
  }
  return $block;
}

/**
 * Social Block
 * @return null
 */
function _etype_social_content() {
  $output = '
<div id="social">
    <ul class="social-links">';
  $facebook = theme_get_setting('facebook','cni');
  $twitter = theme_get_setting('twitter','cni');
  $pinterest = theme_get_setting('pinterest','cni');
  if ( ! empty($facebook)) {
    $output .= '<li><a class="facebook" href="https://www.facebook.com/' . $facebook . '"></a></li>';
  }
  if ( ! empty($twitter)) {
    $output .= '<li><a class="twitter" href="https://twitter.com/' . $twitter . '"></a></li>';
  }
  if ( ! empty($pinterest)) {
    $output .= '<li><a class="pinterest" href="https://www.pinterest.com/' . $pinterest . '"></a></li>';
  }
  $output .= '</ul></div>';
  return $output;
}

/**
 * Follow Block
 * @return null
 */
function _etype_follow_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');
  $twitter = theme_get_setting('twitter','cni');
  $pinterest = theme_get_setting('pinterest','cni');
  if ( ! empty($facebook)) {
    $output .= '<div class="facebook"><a href="https://www.facebook.com/' . $facebook . '">Like us on Facebook</a></div>';
  }
  if ( ! empty($twitter)) {
    $output .= '<div class="twitter"><a href="https://twitter.com/' . $twitter . '">Follow us on Twitter</a></div>';
  }
  if ( ! empty($pinterest)) {
    $output .= '<div class="pinterest"><a href="https://www.pinterest.com/' . $pinterest . '">Follow us on Pinterest</a></div>';
  }
  return $output;
}

/**
 * @return string
 */
function _etype_facebook_content() {
  $output = '';
  $facebook = theme_get_setting('facebook','cni');

  if ( ! empty($facebook)) {
    $output .= '
 <div class="fb-page" data-href="https://www.facebook.com/' . $facebook . '" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
    ';
  }

  return $output;
}

/**
 * @return string
 */
function _etype_twitter_content() {
  $output = '';
  $twitter = theme_get_setting('twitter','cni');
  $twitter_widget_id = theme_get_setting('twitter_widget_id','cni');

  if ( ! empty($twitter)) {
    $output .= '
<a class="twitter-timeline" href="https://twitter.com/' . $twitter . '"';
    if (! empty ($twitter_widget_id)) {
      $output.= ' data-widget-id="' . $twitter_widget_id . '"';
    }
    $output .= '>Tweets by @' . $twitter . '</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    ';
  }

  return $output;
}

function _etype_e_edition_content() {
  $e_edition = theme_get_setting('e_edition','cni');
  $site_name = variable_get('site_name', 'Drupal');
  $arr = preg_split("/ID[0-9]+/", $e_edition);
  $fixed = $arr[0];

  $output= '
<p class="rtecenter" style="text-align: center;"><a href="http://etypeservices.com/' . $e_edition . '/"><img src="http://etypeservices.com/LandingPageImages/' . $fixed . '/currentpg1.jpg" width="193"></a></p><h4 class="rtecenter" style="text-align: center;"><a href="http://etypeservices.com/' . $e_edition . '/">Click here to read ' . $site_name . '</a></h4>
';
  return $output;
}

$ownlocal_path = drupal_get_path('module', 'etype') . '/ownlocal/ownlocal.js';
if (file_exists($ownlocal_path)) {
    drupal_add_js(drupal_get_path('module', 'etype') . '/ownlocal/ownlocal.js', 'file');
    drupal_add_css(drupal_get_path('module', 'etype') . '/ownlocal/ownlocal.css', array('group' => CSS_THEME, 'type' => 'file'));

}


function etype_menu() {

    $items = array();

    /* add e-Edition link to user menu */
    $items['e-edition'] = array(
        'title' => 'e-Edition',
        'description' => 'Link to e-Edition.',
        'page callback' => '_etype_e_edition',
        'access arguments' => array('access content'),
        'menu_name' => 'user-menu',
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function _etype_e_edition() {
    /* redirect to e-Edition */
    $e_edition = theme_get_setting('e_edition', 'cni');
    $path = 'http://etypeservices.com/' . $e_edition . '/';
    drupal_goto($path);
}

