<?php

/**
 * @file
 * Integrate Pico system with site.
 */

/**
 * Implements hook_menu().
 */
function etype_pico_menu() {

  $items = [];

  $items['pico-login'] = [
    'title' => 'Log In',
    'description' => 'Log In with Pico',
    'menu_name' => 'user-menu',
    'page callback' => 'etype_pico_dummy',
    'access arguments' => ['access content'],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['pico-subscribe'] = [
    'title' => 'Subscribe',
    'description' => 'Subscribe with Pico',
    'menu_name' => 'user-menu',
    'page callback' => 'etype_pico_dummy',
    'access arguments' => ['access content'],
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['admin/config/etype/etype_pico/settings'] = [
    'title' => 'Pico Settings',
    'description' => 'Pico integration settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_pico_admin'],
    'file' => 'etype_pico.admin.inc',
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

function etype_pico_dummy() {
  //
}

/**
 * Implements hook_preprocess_html().
 *
 * @param $variables
 */
function etype_pico_preprocess_html(&$variables) {
  $etype_picoPublisherId = variable_get('etype_picoPublisherId');
  if (!empty($etype_picoPublisherId)) {
    $picoOn = 'false';
    $picoType = 'page';
    $pico_head_script = [
      '#type' => 'markup',
      '#markup' => '<script>
(function(p,i,c,o){var n=new Event("pico-init");i[p]=i[p]||function(){(i[p].queue=i[p].queue||[]).push(arguments)},i.document.addEventListener("pico-init",function(e){var t=i.Pico.getInstance(e,{publisherId:o,picoInit:n},i);t.handleQueueItems(i[p].queue),i[p]=function(){return t.handleQueueItems([arguments])}},!1);var e=i.document.createElement("script"),t=i.document.getElementsByTagName("script")[0];e.async=1,e.src=c,e.onload=function(e){return i.Pico.getInstance(e,{publisherId:o,picoInit:n},i)},t.parentNode.insertBefore(e,t)})("pico",window,"https://widget.pico.tools/wrapper.min.js","' . $etype_picoPublisherId . '");
</script>',
    ];
    drupal_add_html_head($pico_head_script, 'pico');
    drupal_add_js(drupal_get_path('module', 'etype_pico') . '/js/etype_pico.js');
    drupal_add_css(drupal_get_path('module', 'etype_pico') . '/css/etype_pico.css');

    $node = menu_get_object();
    if ($node && isset($node->nid)) {
      if ($node->type == 'article') {
        $tids = [];
        $names = [];
        $picoOn = 'true';
        $picoType = 'article';
        if (count($node->field_section["und"]) > 0) {
          foreach ($node->field_section["und"] as $v) {
            $tids[] = $v['tid'];
          }
          $terms = taxonomy_term_load_multiple($tids);
          foreach ($terms as $term) {
            $names[] = $term->name;
          }
        }
        $picoCategories = json_encode($names);
        $variables['body_script'] = <<<EOF
<script>
var pageInfo = {
	article: $picoOn,
	post_id: $node->nid,
	post_type: $picoType,
	taxonomies: { tags: $picoCategories },
	url: window.location.href
};
window.pico('visit', pageInfo);
</script>
EOF;
      }
    }
  }
}
